import { reactive } from 'vue'
export const store = reactive({
  data: [],
  si: [],
  bk: [],
  bx: [],
  q: [],
  m: [],
  mreading: [],
  bkreading: [],
  bkwriting: [],
  bkmath: [],
  bkscore: [],
  qmath: [],
  qreading: [],
  qwriting: [],
  siwriting: [],
  sireading: [],
  simath: [],
  bxmath: [],
  bxreading: [],
  bxwriting: [],
  mmath: [],
  mwriting: [],
  mmathavg: [],
  mreadingavg: [],
  mwritingavg: [],
  barData: [],
  readingscore: []
})
